### ISSUE TITLE
incomplete error msg

### ISSUE THREAD

**Issue by micalevisk** [H4ad/tp-cli#5]
![image](https://user-images.githubusercontent.com/13461315/222981430-d03cde65-8183-4dae-b841-776053d3771f.png)

https://github.com/H4ad/tp-cli/blob/ec293832448667df0a26ba6657e259b4a0add881/src/commands/generate/index.ts#L46

I believe that something was missed in the above error msg

**Comment by H4ad** [comment]
Oh, try run `tp local <template-name>`, I think I forgot to include this description in the error.
